# Generated by Django 4.2.6 on 2023-10-30 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30, verbose_name="имя")),
                ("last_name", models.CharField(max_length=30, verbose_name="фамилия")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("note", models.CharField(max_length=300, verbose_name="комментарий")),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="содержимое")),
                ("title", models.CharField(max_length=150, verbose_name="заголовок")),
            ],
        ),
        migrations.CreateModel(
            name="Periods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="название")),
                (
                    "pattern",
                    models.CharField(max_length=20, verbose_name="cron-шаблон"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("started", "Запущена"),
                            ("finished", "Завершена"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="время начала")),
                ("end_time", models.DateTimeField(verbose_name="время окончания")),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailings.message",
                        verbose_name="Содержание",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailings.periods",
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        to="mailings.client", verbose_name="получатели"
                    ),
                ),
            ],
        ),
    ]
