# Generated by Django 4.2.6 on 2023-10-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_mailinglog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "клиент", "verbose_name_plural": "клиенты"},
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={"verbose_name": "рассылка", "verbose_name_plural": "рассылки"},
        ),
        migrations.AlterModelOptions(
            name="mailinglog",
            options={"verbose_name": "лог", "verbose_name_plural": "логи"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "письмо", "verbose_name_plural": "письма"},
        ),
        migrations.AlterModelOptions(
            name="periods",
            options={"verbose_name": "период", "verbose_name_plural": "периоды"},
        ),
        migrations.AlterField(
            model_name="periods",
            name="pattern",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="cron-шаблон"
            ),
        ),
    ]
