# Generated by Django 4.2.6 on 2023-10-31 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_alter_client_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="recipients",
        ),
        migrations.AlterField(
            model_name="mailing",
            name="content",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="mailings.message",
                verbose_name="Письмо",
            ),
        ),
        migrations.CreateModel(
            name="Audience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="название")),
                (
                    "recipients",
                    models.ManyToManyField(
                        to="mailings.client", verbose_name="получатели"
                    ),
                ),
            ],
            options={
                "verbose_name": "аудитория",
                "verbose_name_plural": "аудитории",
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="audience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mailings.audience",
                verbose_name="аудитория",
            ),
        ),
    ]
