# Generated by Django 4.2.6 on 2023-11-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0008_alter_mailinglog_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="content",
        ),
        migrations.AddField(
            model_name="mailing",
            name="message_body",
            field=models.TextField(default="example", verbose_name="текст рассылки"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailing",
            name="message_title",
            field=models.CharField(
                default="example", max_length=150, verbose_name="заголовок"
            ),
            preserve_default=False,
        ),
    ]
