# Generated by Django 4.2.6 on 2023-11-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0009_remove_mailing_content_mailing_message_body_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
