# Generated by Django 4.2.6 on 2023-11-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0011_alter_mailing_audience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="note",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="комментарий"
            ),
        ),
    ]
