# Generated by Django 4.2.6 on 2023-11-22 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailings", "0014_alter_mailing_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="audience",
            name="creator",
            field=models.ForeignKey(
                default=7,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="создал",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="creator",
            field=models.ForeignKey(
                default=7,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="добавил",
            ),
            preserve_default=False,
        ),
    ]
